2020-08-30 11:49:57,051 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:20:42,189 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:20:53,793 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:20:59,046 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:21:52,343 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:21:55,155 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:24:06,492 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-08-31 13:24:08,776 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:44]
2020-09-03 16:27:15,607 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:14:14,388 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:28:53,047 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:29:35,394 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:29:46,219 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:53:50,274 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:54:38,764 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-03 17:55:11,359 ERROR: Exception on /reset_password_request [POST] [in /media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/email.py", line 15, in send_password_reset_email
    sender = app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-09-03 17:58:03,189 ERROR: Exception on /reset_password_request [POST] [in /media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/email.py", line 15, in send_password_reset_email
    sender = app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-09-03 17:58:19,706 ERROR: Exception on /reset_password_request [POST] [in /media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/routes.py", line 172, in reset_password_request
    send_password_reset_email(user)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/email.py", line 15, in send_password_reset_email
    sender = app.config['ADMINS'][0],
NameError: name 'app' is not defined
2020-09-03 17:58:46,323 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-04 13:39:39,254 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-04 16:14:53,812 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-04 21:08:41,134 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:46]
2020-09-04 21:17:50,049 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:48]
2020-09-04 21:19:32,014 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:48]
2020-09-04 21:25:14,734 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:48]
2020-09-05 16:32:35,852 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:50]
2020-09-05 16:33:08,297 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:50]
2020-09-05 16:33:23,715 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:50]
2020-09-05 16:34:10,899 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:50]
2020-09-05 16:35:38,279 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:50]
