2020-09-05 16:35:41,532 ERROR: Exception on /user/gaurav [GET] [in /media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/routes.py", line 100, in user
    return render_template('user.html', user=user, posts=posts.items, form=form, next_url=next_url, prev_url=prev_url)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/templates/user.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/templates/base.html", line 53, in block "content"
    {% block app_content %}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/templates/user.html", line 37, in block "app_content"
    {% include "_post.html" %}
  File "/media/hemingway/drive_1/gitProjects/flaskProject/app/templates/_post.html", line 12, in top-level template code
    said {{ moment(post.timestam).fromNow() }}:
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_moment.py", line 157, in fromNow
    refresh=refresh)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_moment.py", line 139, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/media/hemingway/drive_1/gitProjects/flaskProject/myvenv/lib/python3.6/site-packages/flask_moment.py", line 135, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
jinja2.exceptions.UndefinedError: 'app.models.Post object' has no attribute 'timestam'
2020-09-05 16:36:03,325 INFO: Microblog startup [in /media/hemingway/drive_1/gitProjects/flaskProject/app/__init__.py:50]
